version: "3"
services:
  app:
    build: .
    ports:
      - 8080:3000
    volumes:
      - ./app:/app
      - ./cert:/cert
      - /app/node_modules
    # command: sh -c "yarn run build && yarn start" # production
    command: yarn dev
    environment:
      HOST: 0.0.0.0
   