version: "3"
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - common_link
    expose:
      - "3000"
    environment:
      NODE_ENV: "production"
      HOST: 0.0.0.0
      VIRTUAL_HOST: "furomap.bonos.work"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "furomap.bonos.work"
      LETSENCRYPT_EMAIL: "tomi@ryou103.com"
      LETSENCRYPT_TEST: "false"
    command: sh -c "yarn run build && yarn start"

networks:
  common_link:
    external: true
