version: "3"
services:
  app:
    build: .
    ports:
      - 8080:3000
    volumes:
      - node_modules:/app/node_modules
      - ./app:/app
      - ./cert:/cert
    # command: sh -c "yarn run build && yarn start" # production
    command: yarn dev
    environment:
      HOST: 0.0.0.0
   
volumes:
  node_modules:
